#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
    systemctl enable dmi-spark-hostname.service >/dev/null 2>&1 || true
    systemctl enable dmi-spark.service >/dev/null 2>&1 || true
    systemctl enable dmi-spark-register.service >/dev/null 2>&1 || true
  fi
fi
